sudo: required
services:
  - docker

before_install:
  - docker build -t iamkumaranca/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true iamkumaranca/docker-react-course npm run test